steps:
  # Step 0: Compile the Go application
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'main', 'main.go']
    id: 'Compile application'

  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/qwiklabs-gcp-01-86a6bfd1738c/my-repository/hello-cloudbuild:$SHORT_SHA'
      - '.'
    id: 'Build Docker image'

  # Step 2: Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/qwiklabs-gcp-01-86a6bfd1738c/my-repository/hello-cloudbuild:$SHORT_SHA'
    id: 'Push Docker image'

images:
  - 'europe-west1-docker.pkg.dev/qwiklabs-gcp-01-86a6bfd1738c/my-repository/hello-cloudbuild:$SHORT_SHA'
